name: build & release mesa-llvm-mini
concurrency:
  group: "build-${{ github.ref }}"
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 5 1/7 * *"
  workflow_dispatch:

jobs:
  build:
    name: "Build: mesa-llvm-mini (${{ matrix.arch }})"
    permissions:
      actions: read
      security-events: write
      contents: write
    runs-on: "${{ matrix.runs-on }}"
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
          - arch: aarch64
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
      - uses: actions/checkout@v6

      - name: prepare container
        run: /bin/sh ./bin/prepare-build
      - name: build package
        run: makepkg -fs --noconfirm
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "mesa-llvm-mini-${{ matrix.arch }}"
          path: "*.pkg.tar.*"

  release:
    name: "release"
    if: github.ref_name == 'main'
    needs: [build]
    permissions:
      actions: read
      security-events: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: "*"
          merge-multiple: true

      - name: release
        uses: softprops/action-gh-release@v2.3.3
        with:
          name: "Continuous build"
          tag_name: continuous
          prerelease: false
          make_latest: true
          target_commitish: "${{ github.sha }}"
          files: |
            *.pkg.tar.*
